#!/bin/sh

PATH=$PATH:/usr/local/bin

KUBERNETES_PUBLIC_ADDRESS=${KUBERNETES_PUBLIC_ADDRESS:-127.0.0.2}

hostlist() {
    cat << EOF
    "worker0",
    "worker1",
    "worker2",
    "ip-10-240-0-20",
    "ip-10-240-0-21",
    "ip-10-240-0-22",
    "10.32.0.1",
    "10.240.0.10",
    "10.240.0.11",
    "10.240.0.12",
    "10.240.0.20",
    "10.240.0.21",
    "10.240.0.22",
    "$KUBERNETES_PUBLIC_ADDRESS",
    "127.0.0.1"
EOF
}

single=$(hostlist | tr -d '[:space:]' | tr -d '"') 
#hosts=$(hostlist | tr -d '[:space:]')

cd /mnt/shared

  #"hosts": [ $hosts ],
cat > kubernetes-csr.json <<EOF
{
  "key": {
    "algo": "rsa",
    "size": 2048
  },
  "names": [
    {
      "C": "US",
      "L": "Alameda",
      "O": "Kubernetes",
      "OU": "Cluster",
      "ST": "California"
    }
  ]
}
EOF

cfssl gencert -initca ca-csr.json | cfssljson -bare ca

#cfssl gencert \
cfssl gencert -hostname=$single \
  -ca=ca.pem \
  -ca-key=ca-key.pem \
  -config=ca-config.json \
  -profile=kubernetes \
  kubernetes-csr.json | cfssljson -bare kubernetes

exit

cat > kubernetes-csr.json <<EOF
{
  "CN": "kubernetes",
  "hosts": [
    "worker0",
    "worker1",
    "worker2",
    "ip-10-240-0-20",
    "ip-10-240-0-21",
    "ip-10-240-0-22",
    "10.32.0.1",
    "10.240.0.10",
    "10.240.0.11",
    "10.240.0.12",
    "10.240.0.20",
    "10.240.0.21",
    "10.240.0.22",
    "$KUBERNETES_PUBLIC_ADDRESS",
    "127.0.0.1"
  ],
  "key": {
    "algo": "rsa",
    "size": 2048
  },
  "names": [
    {
      "C": "US",
      "L": "Alameda",
      "O": "Kubernetes",
      "OU": "Cluster",
      "ST": "California"
    }
  ]
}
EOF

cat > kubernetes-csr.json <<EOF
{
  "CN": "kubernetes",
  "hosts": [ $hostlist ],
  "key": {
    "algo": "rsa",
    "size": 2048
  },
  "names": [
    {
      "C": "US",
      "L": "Alameda",
      "O": "Kubernetes",
      "OU": "Cluster",
      "ST": "California"
    }
  ]
}
EOF

        Names        []Name     `json:"names" yaml:"names"`
143     Hosts        []string   `json:"hosts" yaml:"hosts"`
144     KeyRequest   KeyRequest `json:"key,omitempty" yaml:"key,omitempty"`
145     CA           *CAConfig  `json:"ca,omitempty" yaml:"ca,omitempty"`
146     SerialNumber string     `json:"serialnumber,omitempty" yaml:"serialnumber,omitempty"`
147 
